apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ajdann/argocd
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: brooooooooooooooooooooooo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true # enable automatic sync
      prune: true # enable automatic deletion of resources
