apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/operations/logging/kibana
    repoURL: 'https://github.com/ajdann/argocd'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: operations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
