apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: hello-world
spec:
  project: default
  source:
    repoURL: https://github.com/ajdann/argocd
    targetRevision: HEAD
    path: apps/hello-world
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true # enable automatic sync
      prune: true # enable automatic deletion of resources
