apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operations
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Operations go here

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false




